language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/kerimkaan/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "IRremote,Adafruit Unified Sensor,DHT sensor library"
  
script:
  - build_main_platforms
notifications:
  email:
    on_success: change
    on_failure: change
