
{
  "language": "python",
  "python": "2.7",
  "sudo": false,
  "cache": {
    "directories": [
      "~/.platformio"
    ]
  },
  "env": "PLATFORMIO_CI_SRC=/ PLATFORMIO_BUILD_FLAGS=\"-DSEND_AIWA_RC_T501\"",
  "install": [
    "pip install -U platformio"
  ],
  "script": [
    "platformio ci --lib=\".\" --board=uno --board=leonardo --board=pro16MHzatmega168 --board=btatmega328"
  ],
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
