language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=Garduino.ino
    - PLATFORMIO_CI_SRC=/IROptional/IROptional.ino
    # - ...

install:
    - pip install -U platformio

    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/416/TinyGPS
    # http://platformio.org/lib/show/417/SPI4Teensy3
    - platformio lib -g install 19 4

script:
    - platformio ci --board=uno  --board=leonardo --board=pro16MHzatmega168 --board=btatmega328 --lib="."
