language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=Garduino.ino
    - PLATFORMIO_CI_SRC=IROptional/IROptional.ino
    # - ...

install:
    - pip install -U platformio

    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/19/DHT%20sensor%20library
    # http://platformio.org/lib/show/4/IRremote

    - platformio lib -g install 19 4

script:
    - platformio ci --board=uno  --board=leonardo --board=megaatmega2560 --board=megaatmega1280 --lib="."
